export const rows = [
	[
	  'a<b>p</b>a',
	  'a<b>t</b>a',
	  'a<b>k</b>a',
	  'a<b>f</b>a',
	  'a<b>s</b>a',
	  'a<b>c</b>a',
	],
	[
	  'a<b>b</b>a',
	  'a<b>d</b>a',
	  'a<b>g</b>a',
	  'a<b>v</b>a',
	  'a<b>z</b>a',
	  'a<b>j</b>a',
	],
	[
	  'a<b>m</b>a',
	  'a<b>l</b>a',
	  'a<b>n</b>a',
	  'a<b>r</b>a',
	  ,
	  'a<b>x</b>a',
	  "a<b>'</b>a",
	],
	['a', 'e', 'i', 'o', 'u', 'y'],
	[],
	['aia', 'aua'],
	['au', 'ai', 'ei', 'oi'],
  ]